### ISSUE TITLE
Support for boulders, spawns, ores, etc

### ISSUE THREAD

**Issue by bend-n** [JeanJPNM/mindustry-schematic-parser#11]
`Error: the block is not registered not exist` is annoying, when the block clearly exists, and the mindustry schematic import can parse it.

**Comment by bendnuts** [comment]
hello?

**Comment by JeanJPNM** [comment]
How is this even possible, schematics shouldn't contain non building blocks

**Comment by bendnuts** [comment]
uhhh

**Comment by bend-n** [comment]
[a.msch.zip](https://github.com/JeanJPNM/mindustry-schematic-parser/files/8509956/a.msch.zip)

**Comment by bend-n** [comment]
> How is this even possible, schematics shouldn't contain non building blocks

"shouldn't" isnt the question here. they *can*.

**Comment by JeanJPNM** [comment]
the tag lol

**Comment by JeanJPNM** [comment]
> `Error: the block is not registered not exist` is annoying, when the block clearly exists, and the mindustry schematic import can parse it.

I put that error there because I consider it better than silently returning something like an `UnknownBlock`. Because you can know the parser cannot identify the block.

**Comment by JeanJPNM** [comment]
Done, try version 4.1.6

**Comment by bend-n** [comment]
breaks on water

**Comment by bend-n** [comment]
not to  mention ores.... this just adds support for environment blocks

**Comment by JeanJPNM** [comment]
Those are all environment "blocks", to make it possible for me to debug the problem you need to send the error logs and preferentially the schematic that was being parsed when the error occurred

**Comment by JeanJPNM** [comment]
You didn't provide any useful information, so I'm unable to debug the issue

**Comment by bend-n** [comment]
```
file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:663
        throw new Error(`The block "${code}" could not be found in the registry`);
              ^

Error: The block "water" could not be found in the registry
    at Function.fromCode (file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:663:15)
    at decodeBlocks (file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:4133:29)
    at decodeSchematic (file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:4291:20)
    at Function.decode (file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:4399:30)
    at file:///home/bendn/blocks/schem_image/msch.js:8:29
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```
[a.msch.txt](https://github.com/JeanJPNM/mindustry-schematic-parser/files/8644168/a.msch.txt)

**Comment by JeanJPNM** [comment]
Try it with version 4.1.7. Also don't use `fuck@you` as a tag on the schematics you share in the future.

**Comment by bend-n** [comment]
> Try it with version 4.1.7. Also don't use `fuck@you` as a tag on the schematics you share in the future.

oh, hehe, my generator adds that.
anyways, it works now, thanks!
