### ISSUE TITLE
im confused

### ISSUE THREAD

**Issue by bend-n** [JeanJPNM/mindustry-schematic-parser#6]
as someone who doesnt work with javascript, nor typescript, how the hell do you run the example code? i tried noding it... " not a module, cant import " ...

**Comment by JeanJPNM** [comment]
I've released a fix for what may be the cause of your issue, does the issue persist? If it does, please send a full error log.

**Comment by bend-n** [comment]
![image](https://user-images.githubusercontent.com/70787919/155077643-935e87f5-85c1-49c2-90e3-7339b195d2bc.png)

**Comment by bend-n** [comment]
could you just tell me how its supposed to be run?

**Comment by JeanJPNM** [comment]
Just put `"type": "module"` inside your package.json file.

BUT before leaving, please note that issues can happen due to incorrect user configuration (like this one). Please search more about your problem before opening an issue in the repository of whathever tool you are using.
It's also worth mentioning that logs should be send as text, not images.

**Comment by JeanJPNM** [comment]
Also, read the error messages, the answer was right there.

**Comment by bend-n** [comment]
i tried making a package.json.

**Comment by bend-n** [comment]
adding a package.json just gives me
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/bendn/node_modules/mindustry-schematic-parser/dist/esm/arc' is not supported resolving ES modules imported from /home/bendn/node_modules/mindustry-schematic-parser/dist/esm/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:390:17)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///home/bendn/node_modules/mindustry-schematic-parser/dist/esm/arc'
}

Node.js v17.5.0
```

**Comment by JeanJPNM** [comment]
Yeah, that's the error I mentioned on the first message, updating to version 4.1.3 should fix it.

**Comment by bend-n** [comment]
okay

**Comment by bend-n** [comment]
```name:  3x6 Sand to Scrap
description:  description go  brrrr
power balance:  -240
item cost: { copper: 269, lead: 235 }
/home/bendn/schem_image/node_modules/canvas/lib/image.js:91
  SetSource.call(img, src)
            ^

Error: ENOENT, No such file or directory '/home/bendn/schem_image/assets/sprites/blocks/crafting/pulverizer.png'
    at setSource (/home/bendn/schem_image/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/home/bendn/schem_image/node_modules/canvas/lib/image.js:62:9)
    at /home/bendn/schem_image/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at Object.loadImage (/home/bendn/schem_image/node_modules/canvas/index.js:23:10)
    at RenderingInfo.getAsset (file:///home/bendn/schem_image/node_modules/mindustry-schematic-parser/dist/index.mjs:424:27)
    at RenderingInfo.blockAsset (file:///home/bendn/schem_image/node_modules/mindustry-schematic-parser/dist/index.mjs:446:21)
    at Pulverizer.render (file:///home/bendn/schem_image/node_modules/mindustry-schematic-parser/dist/index.mjs:659:38)
    at Pulverizer.draw (file:///home/bendn/schem_image/node_modules/mindustry-schematic-parser/dist/index.mjs:946:20)
    at Schematic.render (file:///home/bendn/schem_image/node_modules/mindustry-schematic-parser/dist/index.mjs:4054:30) {
  errno: 2,
  code: 'ENOENT',
  path: '/home/bendn/schem_image/assets/sprites/blocks/crafting/pulverizer.png',
  syscall: 'fopen'
}

Node.js v17.5.0
```
cool!

**Comment by JeanJPNM** [comment]
Sorry for not making it clear before, you can wrap the error logs around triple backticks (```` ``` ````) so they get special formating like this:

```
Error: something happened.
at files/something.js
```

**Comment by bend-n** [comment]
i thought single backtick was supposed to do that 🤔

**Comment by bend-n** [comment]
do i need to have all the assets in the directory?

**Comment by JeanJPNM** [comment]
Yes, but they usually come within the package, could you share your code? I'm curious to see why the assets are not inside the installed package.

**Comment by bend-n** [comment]
im simply using the thing you put in the readme

**Comment by bend-n** [comment]
i made a new folder, put in the script, put in the package.json, and tried to run it. i thought the assets would be stored in a globally acessible position?

**Comment by bend-n** [comment]
i put the assets in, and it works, but can it be automatically cropped? like without the background and shadow stuff, more like :
![img_90366bbe-5e13-4b73-ad2d-8784660faf4c](https://user-images.githubusercontent.com/70787919/155246629-e8a6366e-e713-433b-a106-ad10ee6c9a80.png)

**Comment by bend-n** [comment]
![image](https://user-images.githubusercontent.com/70787919/155247996-b8ee3d99-f936-4c47-868c-ceaf45e5e273.png)
mass drivers look wrong

**Comment by JeanJPNM** [comment]
> i put the assets in, and it works, but can it be automatically cropped? like without the background and shadow stuff, more like : ![img_90366bbe-5e13-4b73-ad2d-8784660faf4c](https://user-images.githubusercontent.com/70787919/155246629-e8a6366e-e713-433b-a106-ad10ee6c9a80.png)

Disable the background in the rendering options like this:
```js
schematic.toImageBuffer({
  background: false
})
```

**Comment by JeanJPNM** [comment]
> mass drivers look wrong

I didn't know how to replicate the original effect, so I decided to go with a simple image outline function

**Comment by JeanJPNM** [comment]
I updated the README to provide more info on how to use the package.
